server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html index.htm;

    client_max_body_size 50m;   # если SPA сама загружает большие файлы

    location / {
        try_files $uri $uri/ /index.html;
    }
}
